/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Defense_Units;

import MainController.MainController;
import System.Observable;

/**
 *
 * @author tharu
 */

public class Helicopter extends javax.swing.JFrame implements Observable{
    private MainController mainController;
    private int id;
    /**
     * Creates new form Helicopter
     */
    
    public Helicopter(MainController mainController,int id) {
        this.mainController=mainController;
        this.id=id;
        initComponents();
        setTitle("Helicopter");
        MainTitle.setText(id+". HELICOPTER");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaLabel = new javax.swing.JLabel();
        ShootButton = new javax.swing.JButton();
        LaserButton = new javax.swing.JButton();
        MissileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MsgReceiverTXT = new javax.swing.JTextArea();
        TXTField = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();
        EnergySlider = new javax.swing.JSlider();
        SCountLabel = new javax.swing.JLabel();
        ACountLabel = new javax.swing.JLabel();
        PositionCheckBox = new javax.swing.JCheckBox();
        SQuantity = new javax.swing.JSpinner();
        AQuantity = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();
        FuelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AreaLabel.setText("Area Not Cleared");

        ShootButton.setText("SHOOT");
        ShootButton.setEnabled(false);
        ShootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShootButtonActionPerformed(evt);
            }
        });

        LaserButton.setText("LASER OPERATION");
        LaserButton.setEnabled(false);
        LaserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaserButtonActionPerformed(evt);
            }
        });

        MissileButton.setText("MISSILE OPERATION");
        MissileButton.setEnabled(false);
        MissileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissileButtonActionPerformed(evt);
            }
        });

        MsgReceiverTXT.setEditable(false);
        MsgReceiverTXT.setColumns(20);
        MsgReceiverTXT.setRows(5);
        jScrollPane1.setViewportView(MsgReceiverTXT);

        TXTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFieldActionPerformed(evt);
            }
        });
        TXTField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTFieldKeyReleased(evt);
            }
        });

        SendButton.setText("SEND");
        SendButton.setEnabled(false);
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        EnergySlider.setMajorTickSpacing(20);
        EnergySlider.setMinorTickSpacing(10);
        EnergySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        EnergySlider.setPaintLabels(true);
        EnergySlider.setPaintTicks(true);
        EnergySlider.setValue(0);

        SCountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SCountLabel.setText("Soldier Count");

        ACountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ACountLabel.setText("Ammo Count");

        PositionCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PositionCheckBox.setText("Position");
        PositionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionCheckBoxActionPerformed(evt);
            }
        });

        SQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        AQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Message To HeadQuarters :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Messages From HeadQuarters :");

        MainTitle.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        MainTitle.setText("HELICOPTER");

        FuelLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FuelLabel.setText("Fuel ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ShootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MissileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ACountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LaserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(232, 232, 232)
                                .addComponent(PositionCheckBox))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(AreaLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnergySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FuelLabel)
                        .addGap(15, 15, 15)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(MainTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainTitle)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FuelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnergySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AreaLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MissileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LaserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SCountLabel)
                                    .addComponent(SQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ACountLabel)
                                    .addComponent(AQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(PositionCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShootButtonActionPerformed
       mainController.notifyActionsToMain("Helicopter : "+id+" : Shooted");
    }//GEN-LAST:event_ShootButtonActionPerformed

    private void LaserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaserButtonActionPerformed
       mainController.notifyActionsToMain("Helicopter : "+id+" : Laser Activated");
    }//GEN-LAST:event_LaserButtonActionPerformed

    private void MissileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissileButtonActionPerformed
       mainController.notifyActionsToMain("Helicopter : "+id+" : Missile Launched");
    }//GEN-LAST:event_MissileButtonActionPerformed

    private void TXTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFieldActionPerformed

    private void TXTFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFieldKeyReleased
        SendButton.setEnabled(true);
    }//GEN-LAST:event_TXTFieldKeyReleased

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        String text=TXTField.getText();
        TXTField.setText("");
        SendButton.setEnabled(false);
        mainController.notifyMsgToMain("Helicopter : "+id+" : "+text);
    }//GEN-LAST:event_SendButtonActionPerformed

    private void PositionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionCheckBoxActionPerformed
        if(!PositionCheckBox.isSelected()){
            LaserButton.setEnabled(false);
            MissileButton.setEnabled(false);
            ShootButton.setEnabled(false);
        }else{
            mainController.observer.notifyPosition();
        }
    }//GEN-LAST:event_PositionCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACountLabel;
    private javax.swing.JSpinner AQuantity;
    private javax.swing.JLabel AreaLabel;
    private javax.swing.JSlider EnergySlider;
    private javax.swing.JLabel FuelLabel;
    private javax.swing.JButton LaserButton;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JButton MissileButton;
    private javax.swing.JTextArea MsgReceiverTXT;
    private javax.swing.JCheckBox PositionCheckBox;
    private javax.swing.JLabel SCountLabel;
    private javax.swing.JSpinner SQuantity;
    private javax.swing.JButton SendButton;
    private javax.swing.JButton ShootButton;
    private javax.swing.JTextField TXTField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void notifyAreaClear(String text){
        AreaLabel.setText(text);
    }
    
    public void notifyMsgToUnits(String msg){
        MsgReceiverTXT.append(msg+"\n");
    }
    
    public void update(int Position){
        if(PositionCheckBox.isSelected()){
            if(Position>=60){
                LaserButton.setEnabled(true);
                MissileButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=40){
                LaserButton.setEnabled(false);
                MissileButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=20){
                LaserButton.setEnabled(false);
                MissileButton.setEnabled(false);
                ShootButton.setEnabled(true);
            }else{
                LaserButton.setEnabled(false);
                MissileButton.setEnabled(false);
                ShootButton.setEnabled(false);
            }
        }
    }
    
    public int getSCount(){
        return (int) SQuantity.getValue();
    }
    
    public int getACount(){
        return (int) AQuantity.getValue();
    }
    
    public int getFCount(){
        return EnergySlider.getValue();
    }
    
    public int getOCount(){
        return 0;
    };

}
