/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Defense_Units;

import MainController.MainController;
import System.Observable;

/**
 *
 * @author tharu
 */
public class Submarine extends javax.swing.JFrame implements Observable{
    private MainController mainController;
    private int id;
    /**
     * Creates new form Helicopter
     */
    public Submarine(MainController mainController,int id) {
        this.mainController=mainController;
        this.id=id;
        initComponents();
        setTitle("Submarine");
        MainTitle.setText(id+". SUBMARINE");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaLabel = new javax.swing.JLabel();
        TomahawkMButton = new javax.swing.JButton();
        ShootButton = new javax.swing.JButton();
        SonarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MsgReceiverTXT = new javax.swing.JTextArea();
        TXTField = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();
        EnergySlider = new javax.swing.JSlider();
        SCountLabel = new javax.swing.JLabel();
        ACountLabel = new javax.swing.JLabel();
        PositionCheckBox = new javax.swing.JCheckBox();
        SQuantity = new javax.swing.JSpinner();
        AQuantity = new javax.swing.JSpinner();
        TridentMButton = new javax.swing.JButton();
        OxygenSlider = new javax.swing.JSlider();
        EnergyLabel = new javax.swing.JLabel();
        OxygenLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AreaLabel.setText("Area Not Cleared");

        TomahawkMButton.setText("TOMAHAWK MISSILE");
        TomahawkMButton.setEnabled(false);
        TomahawkMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TomahawkMButtonActionPerformed(evt);
            }
        });

        ShootButton.setText("SHOOT");
        ShootButton.setEnabled(false);
        ShootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShootButtonActionPerformed(evt);
            }
        });

        SonarButton.setText("SONAR OPERATION");
        SonarButton.setEnabled(false);
        SonarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SonarButtonActionPerformed(evt);
            }
        });

        MsgReceiverTXT.setEditable(false);
        MsgReceiverTXT.setColumns(20);
        MsgReceiverTXT.setRows(5);
        jScrollPane1.setViewportView(MsgReceiverTXT);

        TXTField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTFieldKeyReleased(evt);
            }
        });

        SendButton.setText("SEND");
        SendButton.setEnabled(false);
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        EnergySlider.setMajorTickSpacing(20);
        EnergySlider.setMinorTickSpacing(10);
        EnergySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        EnergySlider.setPaintLabels(true);
        EnergySlider.setPaintTicks(true);
        EnergySlider.setValue(0);

        SCountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SCountLabel.setText("Soldier Count");

        ACountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ACountLabel.setText("Ammo Count");

        PositionCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PositionCheckBox.setText("Position");
        PositionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionCheckBoxActionPerformed(evt);
            }
        });

        SQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        AQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        TridentMButton.setText("TRIDENT-2 MISSILE");
        TridentMButton.setEnabled(false);
        TridentMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TridentMButtonActionPerformed(evt);
            }
        });

        OxygenSlider.setMajorTickSpacing(20);
        OxygenSlider.setMinorTickSpacing(10);
        OxygenSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        OxygenSlider.setPaintLabels(true);
        OxygenSlider.setPaintTicks(true);
        OxygenSlider.setValue(0);

        EnergyLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EnergyLabel.setText("Energy ");

        OxygenLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OxygenLabel.setText("Oxygen");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Message To HeadQuarters :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Messages From HeadQuarters :");

        MainTitle.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        MainTitle.setText("SUBMARINE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ShootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TomahawkMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SonarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TridentMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ACountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PositionCheckBox))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(AreaLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EnergySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnergyLabel))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OxygenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OxygenLabel))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(MainTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainTitle)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACountLabel)
                    .addComponent(AQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnergyLabel)
                    .addComponent(OxygenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ShootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SonarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SCountLabel)
                                    .addComponent(SQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TomahawkMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TridentMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(PositionCheckBox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(253, 253, 253))
                    .addComponent(EnergySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OxygenSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TomahawkMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TomahawkMButtonActionPerformed
        mainController.notifyActionsToMain("Submarine : "+id+" : Tomahawk Missile Launched");
    }//GEN-LAST:event_TomahawkMButtonActionPerformed

    private void ShootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShootButtonActionPerformed
        mainController.notifyActionsToMain("Submarine : "+id+" : Shooted");
    }//GEN-LAST:event_ShootButtonActionPerformed

    private void SonarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SonarButtonActionPerformed
        mainController.notifyActionsToMain("Submarine : "+id+" : Sonar Activated");
    }//GEN-LAST:event_SonarButtonActionPerformed

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        String text=TXTField.getText();
        TXTField.setText("");
        SendButton.setEnabled(false);
        mainController.notifyMsgToMain("Submarine : "+id+" : "+text);
    }//GEN-LAST:event_SendButtonActionPerformed

    private void TXTFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFieldKeyReleased
        SendButton.setEnabled(true);
    }//GEN-LAST:event_TXTFieldKeyReleased

    private void PositionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionCheckBoxActionPerformed
        if(!PositionCheckBox.isSelected()){
            TridentMButton.setEnabled(false);
            TomahawkMButton.setEnabled(false);
            SonarButton.setEnabled(false);
            ShootButton.setEnabled(false);
        }else{
            mainController.observer.notifyPosition();
        }
    }//GEN-LAST:event_PositionCheckBoxActionPerformed

    private void TridentMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TridentMButtonActionPerformed
        mainController.notifyActionsToMain("Submarine : "+id+" : Trident-2 Missile Launched");
    }//GEN-LAST:event_TridentMButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACountLabel;
    private javax.swing.JSpinner AQuantity;
    private javax.swing.JLabel AreaLabel;
    private javax.swing.JLabel EnergyLabel;
    private javax.swing.JSlider EnergySlider;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JTextArea MsgReceiverTXT;
    private javax.swing.JLabel OxygenLabel;
    private javax.swing.JSlider OxygenSlider;
    private javax.swing.JCheckBox PositionCheckBox;
    private javax.swing.JLabel SCountLabel;
    private javax.swing.JSpinner SQuantity;
    private javax.swing.JButton SendButton;
    private javax.swing.JButton ShootButton;
    private javax.swing.JButton SonarButton;
    private javax.swing.JTextField TXTField;
    private javax.swing.JButton TomahawkMButton;
    private javax.swing.JButton TridentMButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
     public void notifyAreaClear(String text){
        AreaLabel.setText(text);
    }
     
     public void notifyMsgToUnits(String msg){
        MsgReceiverTXT.append(msg+"\n");
    }
     
    public void update(int Position){
        if(PositionCheckBox.isSelected()){
            if(Position>=80){
                TridentMButton.setEnabled(true);
                TomahawkMButton.setEnabled(true);
                SonarButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=60){
                TridentMButton.setEnabled(false);
                TomahawkMButton.setEnabled(true);
                SonarButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=40){
                TridentMButton.setEnabled(false);
                TomahawkMButton.setEnabled(false);
                SonarButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=20){
                TridentMButton.setEnabled(false);
                TomahawkMButton.setEnabled(false);
                SonarButton.setEnabled(false);
                ShootButton.setEnabled(true);
            }else{
                TridentMButton.setEnabled(false);
                TomahawkMButton.setEnabled(false);
                SonarButton.setEnabled(false);
                ShootButton.setEnabled(false);
            }
        }
    }
    
    public int getSCount(){
        return (int) SQuantity.getValue();
    }
    
    public int getACount(){
        return (int) AQuantity.getValue();
    }
    
    public int getFCount(){
        return EnergySlider.getValue();
    }
    
    public int getOCount(){
        return OxygenSlider.getValue();
    }

}
