/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Defense_Units;

import MainController.MainController;
import System.Observable;

/**
 *
 * @author tharu
 */

public class Tank extends javax.swing.JFrame implements Observable{
    private MainController mainController;
    private int id;
    /**
     * Creates new form Helicopter
     */
    public Tank(MainController mainController,int id) {
        this.mainController=mainController;
        this.id=id;
        initComponents();
        setTitle("Tank");
        MainTitle.setText(id+". TANK");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaLabel = new javax.swing.JLabel();
        ShootButton = new javax.swing.JButton();
        RadarButton = new javax.swing.JButton();
        MissileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MsgReceiverTXT = new javax.swing.JTextArea();
        TXTField = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();
        EnergySlider = new javax.swing.JSlider();
        SCountLabel = new javax.swing.JLabel();
        ACountLabel = new javax.swing.JLabel();
        PositionCheckBox = new javax.swing.JCheckBox();
        SQuantity = new javax.swing.JSpinner();
        AQuantity = new javax.swing.JSpinner();
        RotateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainTitle = new javax.swing.JLabel();
        FuelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AreaLabel.setText("Area Not Cleared");

        ShootButton.setText("SHOOT");
        ShootButton.setEnabled(false);
        ShootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShootButtonActionPerformed(evt);
            }
        });

        RadarButton.setText("RADAR OPERATION");
        RadarButton.setEnabled(false);
        RadarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadarButtonActionPerformed(evt);
            }
        });

        MissileButton.setText("MISSILE OPERATION");
        MissileButton.setEnabled(false);
        MissileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissileButtonActionPerformed(evt);
            }
        });

        MsgReceiverTXT.setEditable(false);
        MsgReceiverTXT.setColumns(20);
        MsgReceiverTXT.setRows(5);
        jScrollPane1.setViewportView(MsgReceiverTXT);

        TXTField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTFieldKeyReleased(evt);
            }
        });

        SendButton.setText("SEND");
        SendButton.setEnabled(false);
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        EnergySlider.setMajorTickSpacing(20);
        EnergySlider.setMinorTickSpacing(10);
        EnergySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        EnergySlider.setPaintLabels(true);
        EnergySlider.setPaintTicks(true);
        EnergySlider.setValue(0);

        SCountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SCountLabel.setText("Soldier Count");

        ACountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ACountLabel.setText("Ammo Count");

        PositionCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PositionCheckBox.setText("Position");
        PositionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionCheckBoxActionPerformed(evt);
            }
        });

        SQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        AQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        RotateButton.setText("ROTATE SHOOTING");
        RotateButton.setEnabled(false);
        RotateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Message To HeadQuarters :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Messages From HeadQuarters :");

        MainTitle.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        MainTitle.setText("TANK");

        FuelLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FuelLabel.setText("Fuel ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ShootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MissileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RotateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ACountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PositionCheckBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(AreaLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnergySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FuelLabel)
                        .addGap(15, 15, 15)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(MainTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FuelLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AreaLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ShootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MissileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SCountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RadarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RotateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ACountLabel)
                                    .addComponent(AQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PositionCheckBox)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnergySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShootButtonActionPerformed
         mainController.notifyActionsToMain("Tank : "+id+" : Shooted");
    }//GEN-LAST:event_ShootButtonActionPerformed

    private void RadarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadarButtonActionPerformed
        mainController.notifyActionsToMain("Tank : "+id+" : Radar Activated");
    }//GEN-LAST:event_RadarButtonActionPerformed

    private void MissileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissileButtonActionPerformed
        mainController.notifyActionsToMain("Tank : "+id+" : Missile Launched");
    }//GEN-LAST:event_MissileButtonActionPerformed

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        String text=TXTField.getText();
        TXTField.setText("");
        SendButton.setEnabled(false);
        mainController.notifyMsgToMain("Tank : "+id+" : "+text);
    }//GEN-LAST:event_SendButtonActionPerformed

    private void TXTFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFieldKeyReleased
        SendButton.setEnabled(true);
    }//GEN-LAST:event_TXTFieldKeyReleased

    private void PositionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionCheckBoxActionPerformed
        if(!PositionCheckBox.isSelected()){
            RotateButton.setEnabled(false);
            RadarButton.setEnabled(false);
            MissileButton.setEnabled(false);
            ShootButton.setEnabled(false);
        }else{
            mainController.observer.notifyPosition();
        }
    }//GEN-LAST:event_PositionCheckBoxActionPerformed

    private void RotateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotateButtonActionPerformed
        mainController.notifyActionsToMain("Tank : "+id+" : Rotate Shooting Started");
    }//GEN-LAST:event_RotateButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACountLabel;
    private javax.swing.JSpinner AQuantity;
    private javax.swing.JLabel AreaLabel;
    private javax.swing.JSlider EnergySlider;
    private javax.swing.JLabel FuelLabel;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JButton MissileButton;
    private javax.swing.JTextArea MsgReceiverTXT;
    private javax.swing.JCheckBox PositionCheckBox;
    private javax.swing.JButton RadarButton;
    private javax.swing.JButton RotateButton;
    private javax.swing.JLabel SCountLabel;
    private javax.swing.JSpinner SQuantity;
    private javax.swing.JButton SendButton;
    private javax.swing.JButton ShootButton;
    private javax.swing.JTextField TXTField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

     public void notifyAreaClear(String text){
        AreaLabel.setText(text);
    }
     
     public void notifyMsgToUnits(String msg){
        MsgReceiverTXT.append(msg+"\n");
    }
     
    public void update(int Position){
         if(PositionCheckBox.isSelected()){
            if(Position>=80){
                RotateButton.setEnabled(true);
                RadarButton.setEnabled(true);
                MissileButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=60){
                RotateButton.setEnabled(false);
                RadarButton.setEnabled(true);
                MissileButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=40){
                RotateButton.setEnabled(false);
                RadarButton.setEnabled(false);
                MissileButton.setEnabled(true);
                ShootButton.setEnabled(true);
            }else if(Position>=20){
                RotateButton.setEnabled(false);
                RadarButton.setEnabled(false);
                MissileButton.setEnabled(false);
                ShootButton.setEnabled(true);
            }else{
                RotateButton.setEnabled(false);
                RadarButton.setEnabled(false);
                MissileButton.setEnabled(false);
                ShootButton.setEnabled(false);
            }
        }
    }
    
    public int getSCount(){
        return (int) SQuantity.getValue();
    }
    
    public int getACount(){
        return (int) AQuantity.getValue();
    }
    
    public int getFCount(){
        return EnergySlider.getValue();
    }
    
    public int getOCount(){
        return 0;
    };
}
