/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainController;

import java.awt.*;
import javax.swing.*;
import System.Observer;
import javax.swing.text.BadLocationException;

/**
 *
 * @author tharu
 */
public class MainController extends javax.swing.JFrame {

    public Observer observer;

    /**
     * Creates new form MainController
     */
    public Observer getObserver(){
        return observer;
    }
    

    public MainController(Observer observer) {
        this.observer = observer;
        setTitle("Main Controller");
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaClearCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        MsgSenderTXT = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        MsgReceiverTXT = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        InformationTXT = new javax.swing.JTextArea();
        SendPrivateCheckBox = new javax.swing.JCheckBox();
        SendButton = new javax.swing.JButton();
        PositionSlider = new javax.swing.JSlider();
        PositionLabel = new javax.swing.JLabel();
        SCountLabel = new javax.swing.JLabel();
        FCountLabel = new javax.swing.JLabel();
        ACountLabel = new javax.swing.JLabel();
        SetDefense = new javax.swing.JComboBox<>();
        CollectButton = new javax.swing.JButton();
        SCountDataLabel = new javax.swing.JLabel();
        FCountDataLabel = new javax.swing.JLabel();
        ACountDataLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OxygenCountLabel = new javax.swing.JLabel();
        OxygenCountDataLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaClearCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AreaClearCheckBox.setText("Area Clear");
        AreaClearCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AreaClearCheckBoxStateChanged(evt);
            }
        });
        AreaClearCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AreaClearCheckBoxMouseClicked(evt);
            }
        });
        AreaClearCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaClearCheckBoxActionPerformed(evt);
            }
        });

        MsgSenderTXT.setColumns(20);
        MsgSenderTXT.setRows(5);
        MsgSenderTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MsgSenderTXTKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(MsgSenderTXT);

        MsgReceiverTXT.setEditable(false);
        MsgReceiverTXT.setColumns(20);
        MsgReceiverTXT.setRows(5);
        jScrollPane3.setViewportView(MsgReceiverTXT);

        InformationTXT.setEditable(false);
        InformationTXT.setColumns(20);
        InformationTXT.setRows(5);
        jScrollPane4.setViewportView(InformationTXT);

        SendPrivateCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SendPrivateCheckBox.setText("Send Message Private");
        SendPrivateCheckBox.setEnabled(false);
        SendPrivateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendPrivateCheckBoxActionPerformed(evt);
            }
        });

        SendButton.setText("SEND");
        SendButton.setEnabled(false);
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        PositionSlider.setMajorTickSpacing(20);
        PositionSlider.setMinorTickSpacing(10);
        PositionSlider.setPaintLabels(true);
        PositionSlider.setPaintTicks(true);
        PositionSlider.setToolTipText("");
        PositionSlider.setValue(0);
        PositionSlider.setName(""); // NOI18N
        PositionSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PositionSliderStateChanged(evt);
            }
        });

        PositionLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PositionLabel.setText("Position");

        SCountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SCountLabel.setText("Soldier Count");

        FCountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FCountLabel.setText("Fuel/Energy Count");

        ACountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ACountLabel.setText("Ammo Count");

        class MyComboBoxRenderer extends JLabel implements ListCellRenderer
        {
            private String _title;

            public MyComboBoxRenderer(String title)
            {
                _title = title;
            }

            @Override
            public Component getListCellRendererComponent(JList list, Object value,
                int index, boolean isSelected, boolean hasFocus)
            {
                if (index == -1 && value == null) setText(_title);
                else setText(value.toString());
                return this;
            }
        }
        SetDefense.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helicopter", "Tank ", "Submarine" }));
        SetDefense.setRenderer(new MyComboBoxRenderer("SELECT DEFENSE"));
        SetDefense.setSelectedIndex(-1);
        SetDefense.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SetDefenseItemStateChanged(evt);
            }
        });

        CollectButton.setText("COLLECT INFORMATION");
        CollectButton.setEnabled(false);
        CollectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollectButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Messages From Defense Units :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Actions From Defense Units :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Message To Defense Units :");

        OxygenCountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 56)); // NOI18N
        jLabel1.setText("HEAD QUARTERS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(OxygenCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FCountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(SCountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ACountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SCountDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(FCountDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(ACountDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(OxygenCountDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(PositionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PositionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SetDefense, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CollectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AreaClearCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SendPrivateCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel3))))
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SetDefense, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CollectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SCountDataLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FCountDataLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ACountLabel)
                            .addComponent(ACountDataLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OxygenCountLabel)
                            .addComponent(OxygenCountDataLabel))
                        .addGap(29, 29, 29)
                        .addComponent(PositionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(PositionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AreaClearCheckBox)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(SendPrivateCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaClearCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaClearCheckBoxActionPerformed
        if (AreaClearCheckBox.isSelected()) {
            observer.notifyAreaClear("Area Cleared");
        } else if (!AreaClearCheckBox.isSelected()) {
            observer.notifyAreaClear("Area Not Cleared");
        }
    }//GEN-LAST:event_AreaClearCheckBoxActionPerformed

    private void SendPrivateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendPrivateCheckBoxActionPerformed

    }//GEN-LAST:event_SendPrivateCheckBoxActionPerformed

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed

        if (MsgSenderTXT.getText().length() > 0) {
            try {
                int lineCount = MsgSenderTXT.getLineCount();
                int startOffset = MsgSenderTXT.getLineStartOffset(lineCount - 1);
                int endOffset;
                if (lineCount == 1) {
                    endOffset = MsgSenderTXT.getDocument().getLength();
                } else {
                    endOffset = MsgSenderTXT.getLineEndOffset(lineCount - 1);

                    if (endOffset > 0 && MsgSenderTXT.getText(endOffset - 1, 1).equals("\n")) {
                        endOffset--;
                    }
                }
                String lastLineText = MsgSenderTXT.getText(startOffset, endOffset - startOffset).trim();
                MsgSenderTXT.append("\n");
                
                if (!SendPrivateCheckBox.isSelected()) {
                    observer.notifyMsgToUnits(lastLineText);
                }else{
                    observer.returnObject(SetDefense.getSelectedIndex()).notifyMsgToUnits(lastLineText);
                }
            } catch (BadLocationException e) {
                JOptionPane.showMessageDialog(rootPane, "Type In The Next Line");
            }
        }
    }//GEN-LAST:event_SendButtonActionPerformed

    private void AreaClearCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AreaClearCheckBoxStateChanged

    }//GEN-LAST:event_AreaClearCheckBoxStateChanged

    private void AreaClearCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaClearCheckBoxMouseClicked
        // TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_AreaClearCheckBoxMouseClicked

    private void MsgSenderTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MsgSenderTXTKeyReleased
        SendButton.setEnabled(true);
    }//GEN-LAST:event_MsgSenderTXTKeyReleased

    private void PositionSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PositionSliderStateChanged
        int value=PositionSlider.getValue();
        observer.setPosition(value);
        
    }//GEN-LAST:event_PositionSliderStateChanged

    private void SetDefenseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SetDefenseItemStateChanged
        CollectButton.setEnabled(true);
        SendPrivateCheckBox.setEnabled(true);
        if(SetDefense.getSelectedIndex()!=2){
            OxygenCountLabel.setText("");
            OxygenCountDataLabel.setText("");
        }else{
            OxygenCountLabel.setText("Oxygen Count");
        }
        SCountDataLabel.setText("");
        FCountDataLabel.setText("");
        ACountDataLabel.setText("");
    }//GEN-LAST:event_SetDefenseItemStateChanged

    private void CollectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollectButtonActionPerformed
        int index = -1;
        if(SetDefense.getSelectedIndex()==0){
            index=0;
        }else if(SetDefense.getSelectedIndex()==1){
            index=1;
        }else if(SetDefense.getSelectedIndex()==2){
            index=2;            
            OxygenCountDataLabel.setText(observer.returnObject(index).getOCount()+"%");
        }
        SCountDataLabel.setText(observer.returnObject(index).getSCount()+"");
        FCountDataLabel.setText(observer.returnObject(index).getFCount()+"%");
        ACountDataLabel.setText(observer.returnObject(index).getACount()+"");
    }//GEN-LAST:event_CollectButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACountDataLabel;
    private javax.swing.JLabel ACountLabel;
    private javax.swing.JCheckBox AreaClearCheckBox;
    private javax.swing.JButton CollectButton;
    private javax.swing.JLabel FCountDataLabel;
    private javax.swing.JLabel FCountLabel;
    private javax.swing.JTextArea InformationTXT;
    private javax.swing.JTextArea MsgReceiverTXT;
    private javax.swing.JTextArea MsgSenderTXT;
    private javax.swing.JLabel OxygenCountDataLabel;
    private javax.swing.JLabel OxygenCountLabel;
    private javax.swing.JLabel PositionLabel;
    private javax.swing.JSlider PositionSlider;
    private javax.swing.JLabel SCountDataLabel;
    private javax.swing.JLabel SCountLabel;
    private javax.swing.JButton SendButton;
    private javax.swing.JCheckBox SendPrivateCheckBox;
    private javax.swing.JComboBox<String> SetDefense;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    public void notifyMsgToMain(String msg) {
        MsgReceiverTXT.append(msg+"\n");
    }
    
    public void notifyActionsToMain(String msg){
        InformationTXT.append(msg+"\n");
    }
}
